title: a10i
subtitle: Avinash Joshi
description: Father, Husband, Software Engineer who loves to code 👨🏻‍💻. Challenges? Bring 'em on, because It's possible — that's my motto.
githubRepo: https://github.com/avinashjoshi/avinashjoshi.github.io
baseurl: ''

permalink: '/:title'

paginate: 10
paginate_path: 'page/:num'

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md